### ISSUE TITLE
GitHubリポジトリへのリンクのいくつかは404になる

### ISSUE THREAD

**Issue by pitang1965** [kosu27/qin-portfolio#21]
以下は私の環境では404になります。

1. https://github.com/kosu27/next_hasura_firebase_lesson
2. https://github.com/kosu27/react-query-spacex
3. https://github.com/kosu27/firebase_lesson

**Comment by kosu27** [comment]
こちらの3っつがおそらくprivateになっているので404になってるかと思われます

**Comment by pitang1965** [comment]
なるほど。自分専用サイトなら問題なしということでしょうか？

**Comment by kosu27** [comment]
お返事おそくなりました、その認識で大丈夫です！
