### ISSUE TITLE
レビュー(感想)

### ISSUE THREAD

**Issue by kananilai** [kosu27/qin-portfolio#28]
お疲れ様です！

コード拝見させていただきました！
私の方が技術、知識が拙いためあまり良いレビューが出来ずすみません。

1点気になったのは、githubへのリンクが切れている点です！

ApolloClientを使っていないため参考に勉強させていただきます！
ファイル構造などもわかりやすかったのでこちらも参考にさせていただきます！🙇‍♂️

**Comment by kosu27** [comment]
@kananilai 
レビューありがとうございます！
確認させていただきます！👍
