### ISSUE TITLE
【レビュー】デザイン部分コーディング

### ISSUE THREAD

**Issue by shu-illy** [kosu27/qin-portfolio#5]
- View on Twitterボタンとフッターのボーダーがくっついてました！
https://gyazo.com/cbc084eaa98715b9ceea3bc5eb4678c1
- `isGeneral`のgenerarlが何を指しているのかがイメージしにくかったので、もう少し具体的な命名にした方が良いと思います🧐
 https://github.com/kosu27/qin-portfolio/blob/feature-refactoring/src/components/Blog/Blogs.tsx#L8-L11
- ヘッダーの各リンクをホバーするとカーソルがテキストになるので、ポインターにした方がいいですね！
https://gyazo.com/f1937ebe9972a1afeb913e09d497dc18
- ここのdivタグはボーダーを表示するためだけのものですかね？であれば、divタグは消して下のCenterコンポーネントをスタイリングするのでもいいと思いました！
https://github.com/kosu27/qin-portfolio/blob/feature-refactoring/src/components/Footer/Footer.tsx#L21
- types全般：キャメルケースとスネークケースが混在しているので、キャメルケースに統一した方がいいと思います。
https://github.com/kosu27/qin-portfolio/blob/feature-refactoring/src/types/Twitter.ts

**Comment by takeyu1013** [comment]
@shu-illy さんがガッツリレビューされているので、自分からは1点だけ！
- `Layout`コンポーネントなどは`<Layout withTitle>`みたいにして、省略するのもよいかもです！
https://zenn.dev/nownewnao/articles/a3045cb7954d67

`ColorScheme`周りはMantineの機能を活用していて、自分も真似すればよかったと思うくらいいい感じでした。
